version: '3.4'

services:
  client-angular:
    image: algoritmoreemplazopaginas
    container_name: algoritmoreemplazo_container
    build: .
    command: ng serve --host 0.0.0.0
    volumes:
      - .:/project
    ports:
      - 4200:4200
      - 49153:49153
      - 9876:9876
      - 49152:49152




